import type { DecisionRecord } from './types'

export const decisionsContent = {
  title: 'Key Engineering Decisions',
  subtitle: 'The decisions that shaped the architecture and delivery approach.',
  records: [
    {
      id: 'vue-vite',
      title: 'Vue 3 + Vite',
      summary: 'Modern TypeScript SPA with fast dev feedback and lazy-loaded routes.',
      context: 'Assessment requires component-based architecture with TypeScript and testable structure.',
      decision: 'Vue 3 Composition API with Vite as the build tool.',
      alternatives: ['React + Next.js', 'SvelteKit', 'Angular'],
      tradeoffs: ['Testable composables separated from SFCs', 'Fast HMR', 'Native Pinia and Router integration'],
      futureEvolution: 'Consider Nuxt if SSR becomes required.',
    },
    {
      id: 'pinia',
      title: 'Pinia',
      summary: 'Structured feature-level state with testable actions.',
      context: 'Forecast, favorites, settings, and search share application state across routes.',
      decision: 'Pinia stores for feature-level state management.',
      alternatives: ['Vuex', 'Composables only', 'TanStack Query'],
      tradeoffs: ['Clear feature boundaries', 'Mockable store actions', 'Devtools integration'],
      futureEvolution: 'TanStack Query if backend API complexity grows.',
    },
    {
      id: 'open-meteo',
      title: 'Open-Meteo',
      summary: 'Free weather data without API keys or backend proxy.',
      context: 'MVP needs a provider with no billing setup or key management.',
      decision: 'Open-Meteo via client-side adapters for weather and air quality.',
      alternatives: ['OpenWeatherMap', 'WeatherAPI', 'Backend proxy'],
      tradeoffs: ['No keys in client bundle', 'Schema isolated in adapters', 'No SLA on free tier'],
      futureEvolution: 'Backend proxy if rate limits or SLA requirements emerge.',
    },
    {
      id: 'no-backend',
      title: 'No backend',
      summary: 'Static SPA satisfies the requirement without server infrastructure.',
      context: 'No authentication, cross-device sync, or server features in scope.',
      decision: 'Client-side data fetching with localStorage persistence.',
      alternatives: ['Node.js API', 'Serverless functions', 'Firebase'],
      tradeoffs: ['Simple Vercel deployment', 'No cross-device sync', 'No API key protection'],
      futureEvolution: 'Lightweight API layer when sync is needed.',
    },
    {
      id: 'repository-pattern',
      title: 'Repository pattern',
      summary: 'Provider schemas isolated from domain types and UI.',
      context: 'Weather APIs use different response formats; domain logic must not depend on them.',
      decision: 'Repository interfaces with provider-specific adapter implementations.',
      alternatives: ['Direct API calls in stores', 'GraphQL federation', 'Inline mapping'],
      tradeoffs: ['Swappable providers', 'Stable domain types', 'Testable boundaries'],
      futureEvolution: 'Additional provider implementations behind selection strategy.',
    },
    {
      id: 'mapper-pattern',
      title: 'Mapper pattern',
      summary: 'Pure functions translate provider responses into domain models.',
      context: 'Open-Meteo condition codes and field names differ from internal types.',
      decision: 'WeatherMapper and AirQualityMapper as independently tested pure functions.',
      alternatives: ['Mapping inline at call sites', 'Shared transformation utilities', 'ORM-style models'],
      tradeoffs: ['Fixture-based unit tests', 'No network in mapper tests', 'Single transformation point'],
      futureEvolution: 'Mapper registry if multiple providers are supported.',
    },
    {
      id: 'local-storage',
      title: 'LocalStorage',
      summary: 'Persist preferences and favorites without accounts.',
      context: 'Returning users need favorites and settings on the same device.',
      decision: 'Typed LocalStorageRepository for all client-side persistence.',
      alternatives: ['IndexedDB', 'Cookies', 'Session storage'],
      tradeoffs: ['Cross-session persistence', 'No cross-device sync', 'Abstraction enables migration'],
      futureEvolution: 'Backend-synced storage with user accounts.',
    },
    {
      id: 'hero-visuals',
      title: 'Weather-condition hero images',
      summary: 'Condition-based backgrounds instead of city photography.',
      context: 'City images add API dependency, licensing, and inconsistent visuals.',
      decision: 'Bundled assets resolved by WeatherVisualResolver from condition and time.',
      alternatives: ['Unsplash/Pexels API', 'Solid gradients', 'Animated illustrations'],
      tradeoffs: ['No extra network requests', 'Consistent across locations', 'Fixed scrim for contrast'],
      futureEvolution: 'Optional city photography behind feature flag.',
    },
    {
      id: 'vercel',
      title: 'Vercel deployment',
      summary: 'CDN delivery with preview deployments per pull request.',
      context: 'Static SPA needs fast hosting and CI integration.',
      decision: 'Vercel with automatic preview and production deployments.',
      alternatives: ['Netlify', 'GitHub Pages', 'S3 + CloudFront'],
      tradeoffs: ['Preview URLs per PR', 'One-click production deploy', 'SPA fallback required'],
      futureEvolution: 'Edge functions for API proxy or SSR.',
    },
  ] satisfies DecisionRecord[],
}
