import type { RoadmapItemData } from './types'

export const implementationContent = {
  title: 'Implementation Strategy',
  subtitle: 'Epic-based delivery with incremental validation at each stage.',
  items: [
    {
      id: 'foundation',
      name: 'Foundation',
      progress: 100,
      status: 'complete',
      goal: 'Project scaffold, routing, design tokens, and shared UI primitives.',
      deliverables: ['Vue 3 + Vite', 'Tailwind tokens', 'Router + AppShell', 'Shared UI primitives'],
      dependencies: [],
      definitionOfDone: ['App boots with routing', 'Design tokens match mockups', 'Themes work'],
    },
    {
      id: 'infrastructure',
      name: 'Infrastructure',
      progress: 100,
      status: 'complete',
      goal: 'Domain types, repository interfaces, adapters, mappers, and storage.',
      deliverables: ['Entity types', 'Open-Meteo adapters', 'Mappers with tests', 'LocalStorage + cache'],
      dependencies: ['Foundation'],
      definitionOfDone: ['Mappers pass fixture tests', 'Adapters fetch live data', 'Interfaces defined'],
    },
    {
      id: 'search',
      name: 'Search',
      progress: 100,
      status: 'complete',
      goal: 'Location search with debounced suggestions and geolocation.',
      deliverables: ['Debounced search', 'Suggestion list', 'Reverse geocoding', 'Recent searches'],
      dependencies: ['Infrastructure'],
      definitionOfDone: ['Search → dashboard works', 'Geolocation returns place name', 'Recents persist'],
    },
    {
      id: 'forecast',
      name: 'Forecast',
      progress: 100,
      status: 'complete',
      goal: 'Weather dashboard with hero, hourly, daily, and supplementary metrics.',
      deliverables: ['Hero card', 'Hourly section', 'Daily section', 'Air quality, UV, wind metrics'],
      dependencies: ['Infrastructure', 'Search'],
      definitionOfDone: ['All horizons display', 'Current hour aligned', 'States render correctly'],
    },
    {
      id: 'favorites',
      name: 'Favorites',
      progress: 100,
      status: 'complete',
      goal: 'Persisted favorites, reorder, and user preferences.',
      deliverables: ['Favorites CRUD + reorder', 'Unit toggle', 'Theme toggle'],
      dependencies: ['Forecast'],
      definitionOfDone: ['Favorites persist with order', 'Units update all values', 'Theme persists'],
    },
    {
      id: 'quality',
      name: 'Quality',
      progress: 100,
      status: 'complete',
      goal: 'Automated tests covering domain logic, stores, and critical flows.',
      deliverables: ['Mapper/store tests', 'Composable tests', 'Component tests', 'Regression tests'],
      dependencies: ['Forecast', 'Favorites'],
      definitionOfDone: ['Suite passes', 'Critical flows covered', 'No known regressions'],
    },
    {
      id: 'deployment',
      name: 'Deployment',
      progress: 100,
      status: 'complete',
      goal: 'Production build pipeline with Vercel preview and production deployments.',
      deliverables: ['Vite production build', 'Vercel config', 'Preview deployments'],
      dependencies: ['Quality'],
      definitionOfDone: ['Build succeeds', 'Production URL live', 'Preview per PR works'],
    },
  ] satisfies RoadmapItemData[],
}
