import type { RoadmapItemData } from './types'

export const implementationContent = {
  title: 'Building the Application',
  subtitle:
    'Once the architecture and design were defined, I started implementation with Cursor — dividing the project into smaller milestones so I could supervise every generated change and keep the architecture consistent.',
  tool: 'Cursor',
  approach:
    'Rather than asking Cursor to build the entire application in one prompt, I divided the project into smaller milestones. That made it much easier to supervise the generated code and keep the architecture consistent.',
  items: [
    {
      id: 'foundation',
      label: 'Project foundation',
      progress: 100,
      goal: 'Stand up the project skeleton and core conventions.',
      deliverables: ['Vite + Vue 3 + TypeScript scaffold', 'Pinia wired in', 'Folder structure for layers'],
      dependencies: [],
      definitionOfDone: ['App boots locally with a clear project structure'],
    },
    {
      id: 'domain',
      label: 'Domain models',
      progress: 100,
      goal: 'Define the core concepts the application reasons about.',
      deliverables: ['Weather and location types', 'Domain entities', 'Alert types'],
      dependencies: ['Project foundation'],
      definitionOfDone: ['Stable domain types independent of any API provider'],
    },
    {
      id: 'api',
      label: 'API integration',
      progress: 100,
      goal: 'Connect to Open-Meteo through repository adapters and mappers.',
      deliverables: ['Repository interfaces', 'Open-Meteo adapters', 'Mappers'],
      dependencies: ['Domain models'],
      definitionOfDone: ['Weather data flows through repositories, not directly from UI'],
    },
    {
      id: 'state',
      label: 'State management',
      progress: 100,
      goal: 'Coordinate shared application state across screens.',
      deliverables: ['Forecast store', 'Favorites store', 'Settings store'],
      dependencies: ['API integration'],
      definitionOfDone: ['Screens read and update state through predictable store APIs'],
    },
    {
      id: 'design-system',
      label: 'Design system',
      progress: 100,
      goal: 'Translate Stitch mockups into reusable Vue components and tokens.',
      deliverables: ['UI primitives', 'Shared components', 'Tailwind theme tokens'],
      dependencies: ['Project foundation'],
      definitionOfDone: ['Core screens compose shared components instead of one-off styles'],
    },
    {
      id: 'search',
      label: 'Location search',
      progress: 100,
      goal: 'Let a user find and select a location.',
      deliverables: ['Search bar', 'Geocoding lookup', 'Result selection flow'],
      dependencies: ['State management'],
      definitionOfDone: ['A user can search a city and land on its forecast'],
    },
    {
      id: 'forecast',
      label: 'Forecast screens',
      progress: 100,
      goal: 'Show the current, hourly, and daily forecast for a selected location.',
      deliverables: ['Weather hero card', 'Hourly forecast row', 'Daily forecast row'],
      dependencies: ['Location search', 'Design system'],
      definitionOfDone: ['Forecast renders correctly for any searched location'],
    },
    {
      id: 'favorites',
      label: 'Favorites',
      progress: 100,
      goal: 'Let users save and quickly return to locations.',
      deliverables: ['Favorites store', 'Add/remove UI', 'Persisted list'],
      dependencies: ['Forecast screens'],
      definitionOfDone: ['Favorites survive a page refresh'],
    },
    {
      id: 'states',
      label: 'Loading and error states',
      progress: 100,
      goal: 'Handle slow networks and failures gracefully.',
      deliverables: ['Loading skeletons', 'Error states', 'Empty states'],
      dependencies: ['Forecast screens'],
      definitionOfDone: ['Every primary screen has a clear loading and error experience'],
    },
    {
      id: 'testing',
      label: 'Testing',
      progress: 100,
      goal: 'Validate domain logic, mappers, and key user flows.',
      deliverables: ['Unit tests on domain/mapper layers', 'Store and composable tests'],
      dependencies: ['Favorites', 'Loading and error states'],
      definitionOfDone: ['Core business logic covered by automated tests'],
    },
    {
      id: 'documentation',
      label: 'Documentation',
      progress: 100,
      goal: 'Document the reasoning behind the project, not just the code.',
      deliverables: ['Engineering Review page', 'Design system notes', 'Inline component docs'],
      dependencies: ['Testing'],
      definitionOfDone: ['Reviewers can understand decisions without reading the entire codebase'],
    },
    {
      id: 'deployment',
      label: 'Deployment',
      progress: 100,
      goal: 'Make the app reachable without any local setup.',
      deliverables: ['Vercel project', 'Preview deployments', 'Stable production URL'],
      dependencies: ['Documentation'],
      definitionOfDone: ['A reviewer can open a URL and use the app with zero setup'],
    },
  ] satisfies RoadmapItemData[],
}
